default: &default
  :namespace: <%= ENV['ACTIVE_JOB_QUEUE_PREFIX'] %>
  :pidfile: tmp/pids/sidekiq.pid
  :expires: 120
  :concurrency: 5
  :queues:
    - [urgent,  20]
    - [mailers, 10]
    - [default, 10]
    - [utils,    1] # Like sentry

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
