version: '2.4'

services:
  base: &app
    build:
      context: ./rails_app/
      args:
        RUBY_VERSION: '2.7.1'
        NODE_MAJOR: '13'
        BUNDLE_VERSION: '2.1.4'
        PG_MAJOR: '12'
    env_file:
      - ./rails_app/.env
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - .docker/.psqlrc:/root/.psqlrc:ro
      - .docker/.pryrc:/root/.pryrc:ro
    environment:
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - EDITOR=vi
      - HISTFILE=/app/log/.bash_history
      - NODE_ENV=development
      - PG_HOST=postgres
      - PG_PASSWORD=postgres
      - PG_USERNAME=postgres
      - PSQL_HISTFILE=/app/log/.psql_history
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/0
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    depends_on:
      - postgres
      - redis

  app:
    <<: *backend
    command: bundle exec puma -C config/puma.rb
    ports:
      - '5000:5000'

  webpacker:
    <<: *app
    command: ./rails_app/bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - RAILS_ENV=${RAILS_ENV:-development}
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  postgres:
    image: postgres:12
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  sidekiq:
    <<: *backend
    ports:
      - 5100:5100
    environment:
      PORT: 5100
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    command: bundle exec sidekiq -C config/sidekiq.yml

  redis:
    image: redis
    command: redis-server

  grafana:
    image: grafana/grafana:5.2.4
    depends_on:
      - prometheus
    ports:
      - 3000:3000/tcp
    volumes:
      - ./grafana_db:/var/lib/grafana
    user: "1"

  prometheus:
    image: prom/prometheus:v2.4.3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    depends_on:
      - backend

    command:
      - --config.file=/etc/prometheus/prometheus.yml

  rails_stressor:
    build: rails_stressor
    image: rails_stressor
    depends_on:
      - backend
    command: -z 2m -c 15 -m GET http://backend:5000

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:
