# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.6"

gem "activeresource", "~> 5.1"
gem "bootsnap", "~> 1.4"
gem "devise", "~> 4.7"
gem "dotenv-rails", "~> 2.7"
gem "friendly_id", "~> 5.3"
gem "jbuilder", "~> 2.7"
gem "name_of_person", "~> 1.1"
gem "omniauth-github", "~> 1.4"
gem "pg", "~> 1.2"
gem "puma", "~> 4.3"
gem "rails-observers", "~> 0.1.5"
gem "rails", "~> 6.0"
gem "redis-namespace", "~> 1.7"
gem "redis-rails", "~> 5.0"
gem "redis", "~> 4.1"
gem "sass-rails", "~> 6.0"
gem "sentry-raven", "~> 3.0"
gem "sidekiq", "~> 6.0"
gem "skylight", "~> 4.3"
gem "stimulus_reflex", "~> 3.2"
gem "turbolinks", "~> 5.2"
gem "view_component", "~> 2.7"
gem "webpacker", "~> 4.0"
gem "yabeda-rails"
gem "yabeda-sidekiq", "~> 0.1.1"
gem "yabeda-prometheus"
gem "yabeda-puma-plugin"

# https://github.com/yabeda-rb/example-prometheus/blob/d069af50c22eb7446b2eaa939a4daf9ffc4b2869/rails_app/Gemfile#L26
# Since v0.1.4 yabeda-prometheus can work either with official client
# or with GitLab's fork which can handle multi-process application servers
# We'll stick with official one.
gem "prometheus-client"

group :development, :test do
  gem "fasterer", "~> 0.8.3"
  gem "ffaker", "~> 2.15"
  gem "lol_dba", "~> 2.2"
  gem "pry-rails", "~> 0.3.9"
  gem "rails_best_practices", "~> 1.20"
  gem "solargraph", "~> 0.39.7"
end

group :development do
  gem "better_errors", "~> 2.7"
  gem "binding_of_caller", "~> 0.8.0"
  gem "brakeman", "~> 4.8"
  gem "erb_lint", "~> 0.0.33"
  gem "letter_opener", "~> 1.7"
  gem "listen", "~> 3.1", "< 3.2"
  gem "model_probe", "~> 1.0"
  gem "ngrok-tunnel"
  gem "standard", "~> 0.4.6"
  gem "strong_versions", "~> 0.4.4"
  gem "tmuxinator", "~> 2.0"
  gem "tty-box"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development do
  gem "annotate"
end
